In [1]:
import game_v2

In [2]:
game_v2.score_game(game_v2.random_predict)

Ваш алгоритм угадывает число в среднем за: 101 попыток


101

In [3]:
from game_v2 import score_game
from game_v2 import random_predict

In [4]:
score_game(random_predict) #вызов функции

Ваш алгоритм угадывает число в среднем за: 101 попыток


101

In [80]:
import numpy as np

def get_unique_loto(num):
    
    res = list()
    for i in range(num):
        res.append(np.random.choice(np.arange(1, 101), replace=False, size=(5, 5)))
    res = np.array(res)
    return res

result = get_unique_loto(3)
print(result)

[[[ 60  79  11  21  15]
  [ 89  26   6  34  44]
  [ 62  19  67  40  43]
  [ 54  32   8  74  33]
  [ 52  24  65  80  53]]

 [[ 60  92  93  82  30]
  [ 35  63  43  18  86]
  [ 40 100  97  99   4]
  [ 33  70  94   9  44]
  [ 13  52  88  23  67]]

 [[ 66 100  97  83  64]
  [ 15   9  41  88  38]
  [  4  47  61  24  34]
  [ 84  50  56  73  32]
  [ 81  63  11  17  76]]]
